version: "3"
services:
  app:
    build: 
      context: ./
      dockerfile: ./docker/app/app.dockerfile
    container_name: desafio_carrinho_app
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html

  web:
    build:
      context: ./
      dockerfile: ./docker/web/web.dockerfile
    container_name: desafio_carrinho_web
    restart: unless-stopped
    ports:
      - 8080:80
    working_dir: /var/www/html
    volumes:
      - ./src:/var/www/html
    depends_on:
      - app
